In [1]:
%matplotlib inline
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key
import matplotlib.pyplot as plt

In [2]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("Data/WeatherPy_challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description,Rain,Snow
0,0,Salalah,OM,2020-02-24 08:01:40,17.02,54.09,80.60,57,10,3.36,clear sky,0.0,0.0
1,1,Pangnirtung,CA,2020-02-24 08:01:40,66.15,-65.71,-30.26,97,100,2.17,overcast clouds,0.0,0.0
2,2,Bluff,NZ,2020-02-24 08:01:40,-46.60,168.33,63.00,62,100,4.00,overcast clouds,0.0,0.0
3,3,Bambous Virieux,MU,2020-02-24 08:01:41,-20.34,57.76,86.00,66,40,5.82,scattered clouds,0.0,0.0
4,4,Grand Gaube,MU,2020-02-24 08:01:41,-20.01,57.66,86.00,66,40,5.82,scattered clouds,0.0,0.0

In [4]:
city_data_df.dtypes

City_ID                  int64
City                    object
Country                 object
Date                    object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Weather description     object
Rain                   float64
Snow                   float64
dtype: object

In [5]:
type(city_data_df)

pandas.core.frame.DataFrame

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [8]:
#!pip install gmaps

In [9]:
#import sys
#! jupyter nbextension enable --py widgetsnbextension
#! jupyter nbextension enable --py gmaps

In [10]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_choice = input("Do you want it to be raining? (yes/no) ")
snow_choice = input("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [12]:
#rain selection
if rain_choice == "yes":
    rain_yn = city_data_df["Rain"] > 0
elif rain_choice == "no": 
    rain_yn = city_data_df["Rain"] <= 0
else:
    rain_yn = city_data_df["Rain"] >= 0

In [13]:
#snow selection
if snow_choice == "yes":
    snow_yn = city_data_df["Snow"] > 0
elif snow_choice == "no":
    snow_yn = city_data_df["Snow"] <= 0
else:
    snow_yn = city_data_df["Snow"] >= 0

In [14]:
# Filter the dataset to find the cities that fit the criteria.I added dropna() at the end of the filter to remove all values with null values

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp) & rain_yn & snow_yn].dropna()

#I could do it in a separated line
#preferred_cities_df = preferred_cities_df.dropna()

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description,Rain,Snow
0,0,Salalah,OM,2020-02-24 08:01:40,17.02,54.09,80.60,57,10,3.36,clear sky,0.0,0.0
2,2,Bluff,NZ,2020-02-24 08:01:40,-46.60,168.33,63.00,62,100,4.00,overcast clouds,0.0,0.0
3,3,Bambous Virieux,MU,2020-02-24 08:01:41,-20.34,57.76,86.00,66,40,5.82,scattered clouds,0.0,0.0
4,4,Grand Gaube,MU,2020-02-24 08:01:41,-20.01,57.66,86.00,66,40,5.82,scattered clouds,0.0,0.0
7,7,Mataura,NZ,2020-02-24 08:01:41,-46.19,168.86,63.00,62,100,4.00,overcast clouds,0.0,0.0
8,8,Port Elizabeth,ZA,2020-02-24 08:00:10,-33.92,25.57,68.00,56,0,4.70,clear sky,0.0,0.0
10,10,Puerto Ayora,EC,2020-02-24 08:01:42,-0.74,-90.35,77.00,100,74,1.01,broken clouds,0.0,0.0
14,14,Port Alfred,ZA,2020-02-24 08:01:43,-33.59,26.89,68.00,80,0,3.00,clear sky,0.0,0.0
17,17,Bredasdorp,ZA,2020-02-24 08:01:43,-34.53,20.04,71.01,60,40,11.41,scattered clouds,0.0,0.0
21,21,Hilo,US,2020-02-24 08:01:44,19.73,-155.09,71.60,78,20,3.36,few clouds,0.0,0.0

In [15]:
# Create the output file (CSV) with city list
import os

output_data_file = os.path.join("Data","WeatherPy_vacation.csv")

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file)

In [16]:
preferred_cities_df.count()

City_ID                224
City                   224
Country                224
Date                   224
Lat                    224
Lng                    224
Max Temp               224
Humidity               224
Cloudiness             224
Wind Speed             224
Weather description    224
Rain                   224
Snow                   224
dtype: int64

In [17]:
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Weather description    0
Rain                   0
Snow                   0
dtype: int64

In [18]:
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather description,Lat,Lng,Hotel Name
0,Salalah,OM,80.60,clear sky,17.02,54.09,
2,Bluff,NZ,63.00,overcast clouds,-46.60,168.33,
3,Bambous Virieux,MU,86.00,scattered clouds,-20.34,57.76,
4,Grand Gaube,MU,86.00,scattered clouds,-20.01,57.66,
7,Mataura,NZ,63.00,overcast clouds,-46.19,168.86,
8,Port Elizabeth,ZA,68.00,clear sky,-33.92,25.57,
10,Puerto Ayora,EC,77.00,broken clouds,-0.74,-90.35,
14,Port Alfred,ZA,68.00,clear sky,-33.59,26.89,
17,Bredasdorp,ZA,71.01,scattered clouds,-34.53,20.04,
21,Hilo,US,71.60,few clouds,19.73,-155.09,

In [19]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [20]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Weather description,Lat,Lng,Hotel Name
0,Salalah,OM,80.60,clear sky,17.02,54.09,HAMDAN PLAZA HOTEL
2,Bluff,NZ,63.00,overcast clouds,-46.60,168.33,Bluff Homestead - Guesthouse & Campervan Park
3,Bambous Virieux,MU,86.00,scattered clouds,-20.34,57.76,Casa Tia Villa
4,Grand Gaube,MU,86.00,scattered clouds,-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
7,Mataura,NZ,63.00,overcast clouds,-46.19,168.86,Ellie's Villa
8,Port Elizabeth,ZA,68.00,clear sky,-33.92,25.57,39 On Nile Guest House
10,Puerto Ayora,EC,77.00,broken clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
14,Port Alfred,ZA,68.00,clear sky,-33.59,26.89,The Halyards Hotel
17,Bredasdorp,ZA,71.01,scattered clouds,-34.53,20.04,Bredasdorp Country Manor
21,Hilo,US,71.60,few clouds,19.73,-155.09,Hilo Hawaiian Hotel

In [21]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Weather</dt><dd>{Weather description}</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

#in the marker we put locations as argument (eg. x value), and info_box_content as value
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))